import { chromium } from "playwright";
const B = "http://127.0.0.1:4173/e2e/fixtures/restaurant-tour.html?theme=dark&state=";
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1600, height: 1000 }, deviceScaleFactor: 1, colorScheme: "dark", reducedMotion: "reduce", timezoneId: "America/New_York" });
const pg = await ctx.newPage();
pg.on("pageerror", (e) => console.log("ERR", String(e)));
const open = async (s) => { await pg.goto(B + s, { waitUntil: "networkidle" }); await pg.waitForTimeout(800); };
const shot = async (n) => { await pg.waitForTimeout(400); await pg.screenshot({ path: `/tmp/product/x-${n}.png` }); console.log(n); };
await open("conversation");
await pg.locator(".sidebar-account, [aria-label*='ccount']").first().click().catch(e=>console.log('acct',e.message));
await shot("settings");
await open("conversation");
await pg.getByText("Worked for 4m").click(); await shot("work");
await open("conversation");
await pg.locator("button:has-text(\"Artifacts (\")").click(); await shot("artifacts");
await open("done");
await pg.getByText("Split reservations out of InventoryService").click(); await shot("pr");
await open("landing");
await pg.locator("button:has-text(\"Opus 5.5\")").first().click(); await shot("model");
await open("conversation");
const row = pg.locator(".row", { hasText: "Fix flaky checkout test" });
await row.hover();
await pg.getByRole("button", { name: "Conversation actions for Fix flaky checkout test" }).click(); await shot("menu");
await pg.getByRole("menuitem", { name: "Release" }).click(); await shot("release");
await b.close();
