import { chromium } from "playwright";
const out = "/tmp/v09"; import fs from "fs"; fs.mkdirSync(out, { recursive: true });
const b = await chromium.launch();
const pg = await b.newPage({ viewport: { width: 1600, height: 900 } });
const errs = []; pg.on("pageerror", (e) => errs.push(String(e)));
await pg.goto("http://localhost:3909/?seg=pantry&tt=0.5&t=5&mood=9", { waitUntil: "networkidle" });
await pg.waitForSelector(".mv09 .draw .pl", { timeout: 60000, state: "attached" });
await pg.evaluate(() => (window.__mk = 1));
const ok = async (n) => { const r = await pg.evaluate(() => window.__mk === 1); if (!r) console.log("RELOADED before", n); };
await pg.waitForTimeout(2500); await ok("a");
await pg.screenshot({ path: `${out}/a-plotting.png` });
await pg.waitForTimeout(4500); await ok("b");
await pg.mouse.move(10, 10);
await pg.screenshot({ path: `${out}/b-done.png` });
await pg.hover(".mv09 .bom tbody tr:nth-child(2)"); await pg.waitForTimeout(400);
await pg.screenshot({ path: `${out}/c-hover.png` });
const which = process.argv[2] || "4";
await pg.click(`.mv09 .sheets button:nth-of-type(${which})`); await pg.waitForTimeout(2500);
await pg.screenshot({ path: `${out}/d-plot.png` });
await pg.waitForTimeout(4500);
await pg.mouse.move(10, 10); await ok("e");
await pg.screenshot({ path: `${out}/e-r${which}.png` });
await pg.hover(".mv09 .draw .part[data-i='0'] .hit", { force: true }); await pg.waitForTimeout(400);
await pg.screenshot({ path: `${out}/f-hoverpart.png` });
console.log(errs.join("\n") || "no errors");
await b.close();
