"""Write docs/ASSETS.md: every shipped asset with size, dimensions, duration and sha256.
Run from the demo1/ folder: python pipeline/manifest.py  (needs pillow + imageio-ffmpeg)."""
import hashlib, os, re, subprocess
from PIL import Image
import imageio_ffmpeg
FF = imageio_ffmpeg.get_ffmpeg_exe()

def vinfo(p):
    out = subprocess.run([FF, "-hide_banner", "-i", p], capture_output=True, text=True).stderr
    dur = re.search(r"Duration: (\d+):(\d+):([\d.]+)", out)
    v = re.search(r"Video: (\w+).*?, (\w+)(?:\(.*?\))?, (\d+)x(\d+).*?, ([\d.]+) fps", out)
    secs = int(dur[1]) * 3600 + int(dur[2]) * 60 + float(dur[3]) if dur else 0
    return f"{v[3]}×{v[4]}", f"{secs:.2f}s @ {v[5]} fps, {v[1]} {v[2]}" if v else ""

rows = {}
for root in ["site/public", "art", "ref"]:
    for dp, _, fs in os.walk(root):
        for f in sorted(fs):
            p = os.path.join(dp, f); ext = f.rsplit(".", 1)[-1].lower()
            h = hashlib.sha256(open(p, "rb").read()).hexdigest()[:16]
            kb = os.path.getsize(p) // 1024
            if ext == "mp4": dim, extra = vinfo(p)
            elif ext in ("png", "jpg", "jpeg"):
                with Image.open(p) as im: dim, extra = f"{im.width}×{im.height}", im.mode
            else: dim, extra = "", ""
            rows.setdefault(dp, []).append(f"| `{p}` | {kb:,} KB | {dim} | {extra} | `{h}` |")

with open("docs/ASSETS.md", "w") as o:
    o.write("# Asset manifest\n\nEvery shipped asset, generated by `pipeline/manifest.py`. The hash is the first 16 hex digits of its sha256. "
            "These files are the source of truth: a rebuild uses them as-is and only regenerates an asset if it is missing. "
            "Run `python pipeline/manifest.py && git diff docs/ASSETS.md` to prove nothing changed.\n")
    for dp in sorted(rows):
        o.write(f"\n## `{dp}/`\n\n| File | Size | Dimensions | Details | sha256 |\n|---|---|---|---|---|\n" + "\n".join(rows[dp]) + "\n")
print(sum(len(r) for r in rows.values()), "assets")
