import { chromium } from "playwright";
const b = await chromium.launch();
const errs=[];
const pg = await b.newPage({ viewport: { width: 1280, height: 720 } });
pg.on("pageerror", (e) => errs.push(String(e)));
const D="/tmp/polish-chrome/flow";
await pg.goto(`http://localhost:3000/`, { waitUntil: "commit" });
await pg.waitForTimeout(150);
await pg.screenshot({ path: `${D}/1-loader.png` });
await pg.waitForTimeout(4500);
await pg.screenshot({ path: `${D}/2-hint.png` });
await pg.keyboard.type("sudo");
await pg.waitForTimeout(400);
await pg.screenshot({ path: `${D}/3-toast.png` });
await pg.click("#eggs");
await pg.waitForTimeout(300);
await pg.screenshot({ path: `${D}/4-pop.png` });
await pg.mouse.move(1255, 360);
await pg.waitForTimeout(400);
await pg.screenshot({ path: `${D}/5-railhover.png` });
const t0=Date.now();
const p2 = await b.newPage({ viewport: { width: 390, height: 844 } });
await p2.goto(`http://localhost:3000/`, { waitUntil: "networkidle" });
await p2.waitForTimeout(500);
await p2.screenshot({ path: `${D}/6-portrait.png` });
console.log(errs.length?errs:"no errors");
await b.close();
