import { chromium } from "playwright";
const b = await chromium.launch();
const pg = await b.newPage({ viewport: { width: 1600, height: 900 } });
const errs = [];
let loads = 0;
pg.on("load", () => loads++);
pg.on("pageerror", (e) => errs.push(String(e)));
pg.on("console", (m) => m.type() === "error" && errs.push(m.text()));
await pg.goto("http://localhost:3000/?seg=pantry&tt=0.5&t=5&mood=6", { waitUntil: "networkidle" });
await pg.waitForTimeout(3300);
await pg.screenshot({ path: "/tmp/v06/s1.png" });
const bb = await (await pg.$(".mv06 canvas")).boundingBox();
const sx = bb.width / 1640;
const plate = () => pg.mouse.click(bb.x + 572 * sx, bb.y + 385 * sx);
await plate(); await pg.waitForTimeout(1500);
await pg.screenshot({ path: "/tmp/v06/s2.png" });
await pg.click(".mv06-menu button:nth-child(4)"); await pg.waitForTimeout(3600);
await pg.screenshot({ path: "/tmp/v06/s3.png" });
await plate(); await pg.waitForTimeout(1500);
await pg.screenshot({ path: "/tmp/v06/s4.png" });
await pg.click(".mv06-menu button:nth-child(2)"); await pg.waitForTimeout(1000);
await pg.screenshot({ path: "/tmp/v06/s5.png" });
console.log("loads", loads, errs.join("\n") || "no errors");
await b.close();
