import { chromium } from "playwright";
const b = await chromium.launch();
const pg = await b.newPage({ viewport: { width: 1600, height: 900 } });
const errs = [];
pg.on("pageerror", (e) => errs.push(String(e)));
pg.on("console", (m) => m.type() === "error" && errs.push(m.text()));
await pg.goto("http://localhost:3000/?seg=pantry&tt=0.5&t=5&mood=10", { waitUntil: "networkidle" });
await pg.waitForTimeout(2500);
await pg.screenshot({ path: "/tmp/v10/a.png" });
await pg.evaluate(() => document.querySelector(".mv10 .scene").click());
await pg.waitForTimeout(1600);
await pg.screenshot({ path: "/tmp/v10/b_mid.png" });
await pg.waitForTimeout(3500);
await pg.screenshot({ path: "/tmp/v10/b.png" });
await pg.evaluate(() => document.querySelector(".mv10 .list button:nth-child(4)").click());
await pg.waitForTimeout(700);
await pg.screenshot({ path: "/tmp/v10/c_mid.png" });
await pg.waitForTimeout(5500);
await pg.screenshot({ path: "/tmp/v10/c.png" });
await pg.evaluate(() => document.querySelector(".mv10 .scene").click());
await pg.waitForTimeout(3500);
await pg.screenshot({ path: "/tmp/v10/d.png" });
console.log(errs.join("\n") || "no errors");
await b.close();
